//! Generated tonic stubs. The `.proto` files in /proto are the source of truth
//! for the wire contract.

pub mod echo {
    #[allow(clippy::pedantic, reason = "generated by tonic-prost-build")]
    pub mod v1 {
        tonic::include_proto!("echo.v1");
    }
}

pub mod kernel {
    #[allow(clippy::pedantic, reason = "generated by tonic-prost-build")]
    pub mod v1 {
        tonic::include_proto!("kernel.v1");
    }
}

pub mod store {
    #[allow(clippy::pedantic, reason = "generated by tonic-prost-build")]
    pub mod v1 {
        tonic::include_proto!("store.v1");
    }
}

pub mod sync {
    #[allow(clippy::pedantic, reason = "generated by tonic-prost-build")]
    pub mod v1 {
        tonic::include_proto!("sync.v1");
    }
}
