//! Generated tonic stubs. The `.proto` files in /proto are the source of truth
//! for the wire contract.

pub mod echo {
    #[allow(clippy::pedantic, reason = "generated by tonic-prost-build")]
    pub mod v1 {
        tonic::include_proto!("echo.v1");
    }
}
